### ISSUE TITLE
Allow expression to trigger action

### ISSUE THREAD

**Issue by JakeGinnivan** [AdaptiveConsulting/ReactGraph#24]
For example

`engine.Exp(() => vm.CanFoo).Action(()=>vm.FooCommand.RaiseCanExecuteChanged());`

**Comment by odeheurles** [comment]
This should take 2 actions, onNext and onError.
It could optionally have an onComplete handler, called when we tear down the engine

Olivier

**Comment by odeheurles** [comment]
Jake implemented that
